parser: babel-eslint
extends:
  - airbnb-base
plugins:
  - flowtype
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - "**/__tests__/*.js"
  max-len:
    - error
    - code: 120
      ignoreComments: true
  semi:
    - error
    - never
env:
  jest: true
  jasmine: true
  node: true
