language: node_js
node_js:
  - 4
  - 6
  - 7
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
  - e2e/node_modules
script: e2e/run.sh
after_success: npm run coveralls
env:
  - NODE_SASS=3
  - NODE_SASS=4
